name: "atmo_platform"
version: "1.0.0"

profile: "default"

vars:
  processed_path: "{{ env_var('PROCESSED_PATH', '/opt/data/processed') }}"

model-paths: ["models"]

models:
  atmo_platform:
    staging:
      +materialized: view

    marts:
      +materialized: view

    monitoring:
      +materialized: view

seeds:
  atmo_platform:
    identifiants-epci-2024:
      +column_types:
        SIREN: varchar
        code_departement: varchar
        code_region: varchar