name: "default"
version: "1.0.0"

profile: "default"

vars:
  processed_path: "{{ env_var('PROCESSED_PATH', '/opt/data/processed') }}"

model-paths: ["models"]

models:
  atmo_platform:
    staging:
      +materialized: view

    marts:
      +materialized: table