version: 2

models:
  - name: stg_atmo_daily
    description: "Données ATMO nettoyées et dédupliquées, une ligne par commune par jour"
    columns:
      - name: date_ech
        description: "Date de l'indice"
        data_tests:
          - not_null

      - name: code_insee
        description: "Code INSEE de la commune ou EPCI"
        data_tests:
          - not_null

      - name: code_departement
        description: "2 premiers chiffres du code INSEE"
        data_tests:
          - not_null

      - name: code_qual
        description: "Indice global ATMO de 1 à 6"
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6]

      - name: code_no2
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6]

      - name: code_o3
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6]

      - name: code_pm10
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6]

      - name: code_pm25
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6]

      - name: code_so2
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6]

  - name: stg_meteo_daily
    description: "Données météo Open-Meteo nettoyées, une ligne par département par jour"
    columns:
      - name: date_ech
        data_tests:
          - not_null
      - name: code_departement
        data_tests:
          - not_null
      - name: temperature_mean
        data_tests:
          - not_null
      - name: temperature_max
        data_tests:
          - not_null
      - name: temperature_min
        data_tests:
          - not_null
      - name: wind_speed_max
        data_tests:
          - not_null
      - name: weathercode
        data_tests:
          - not_null